# Generated by Django 3.1 on 2020-08-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_choice', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='symptom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_form.symptomchoice'),
        ),
    ]
