# Generated by Django 3.1 on 2020-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0004_auto_20200822_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_choice', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='additional',
            field=models.ManyToManyField(blank=True, null=True, to='test_form.AdditionalInfo'),
        ),
    ]
