# Generated by Django 3.1 on 2020-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0008_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
