# Generated by Django 3.1 on 2020-08-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0009_profile_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
