# Generated by Django 3.1 on 2020-08-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0010_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_tested',
            field=models.BooleanField(default=False),
        ),
    ]
