# Generated by Django 3.1 on 2020-08-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0011_profile_is_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=30, null=True),
        ),
    ]
