# Generated by Django 3.1 on 2020-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0012_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
