# Generated by Django 3.1 on 2020-08-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0013_profile_emergency_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
