# Generated by Django 3.1 on 2020-08-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0014_profile_export_to_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
